version: '3.1'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      target: development
    command: pnpm run start:dev api-gateway
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'


