version: '3.1'

services:
  # api-gateway:
  #   container_name: ecommerce-api-gateway
  #   restart: always
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   external_links:
  #     - mongo
  #     - redis
  #     - rabbitmq
  #     - minio
  #     - mongodb-primary
  #     - mongodb-secondary
  #     - mongodb-arbiter



  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniostorage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    command: redis-server

  rabbitmq:
    image: rabbitmq
    ports:
      - '15672:15672'
      - '5672:5672'
  mongodb-primary:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGODB_ADVERTISED_HOSTNAME : mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123

  mongodb-secondary:
    image: mongo
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME : mongodb-secondary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: example

  mongodb-arbiter:
    image: mongo
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME : mongodb-arbiter
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_REPLICA_SET_KEY: replicasetkey123
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

volumes:
  mongodb_data_container:
  miniostorage:
    driver: local

