
export const USERS_SERVICE = 'USERS_SERVICE';
export const USERS_SERVICE_QUEUE = 'USERS_SERVICE_QUEUE';

export const PRODUCTS_SERVICE = 'PRODUCTS_SERVICE';
export const PRODUCTS_SERVICE_QUEUE = 'PRODUCTS_SERVICE_QUEUE';

export const ORDERS_SERVICE = 'ORDERS_SERVICE';
export const ORDERS_SERVICE_QUEUE = 'ORDERS_SERVICE_QUEUE';

export const PAYMENTS_SERVICE = 'PAYMENTS_SERVICE';
export const PAYMENTS_SERVICE_QUEUE = 'PAYMENTS_SERVICE_QUEUE';

export const SHIPPING_SERVICE = 'SHIPPING_SERVICE';
export const SHIPPING_SERVICE_QUEUE = 'SHIPPING_SERVICE_QUEUE';

export const AUTHENTICATION_SERVICE = 'AUTHENTICATION_SERVICE';
export const AUTHENTICATION_SERVICE_QUEUE = 'AUTHENTICATION_SERVICE_QUEUE';

