/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n";
export type I18nTranslations = {
  validation: {
    IS_NOT_EMPTY: string;
    IS_STRING: string;
  };
};

export type I18nPath = Path<I18nTranslations>;
